// Service worker — offline app shell + runtime cache. Bump CACHE on each release.
const CACHE = 'arcade-v46';
const SHELL = [
  './', './index.html', './app.css', './manifest.webmanifest',
  './icon.svg', './icon-192.png', './icon-512.png', './apple-touch-icon-180.png',
  'https://cdn.tailwindcss.com',
  'https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js',
  'https://unpkg.com/mqtt@5.7.0/dist/mqtt.min.js',
  // MODULES:START (auto-generated by bump-version.sh — do not edit by hand)
  './js/app.js?v=46',
  './js/demos.js?v=46',
  './js/favorites.js?v=46',
  './js/friends.js?v=46',
  './js/i18n.js?v=46',
  './js/identity.js?v=46',
  './js/logic.js?v=46',
  './js/loyalty.js?v=46',
  './js/platform.js?v=46',
  './js/prefs.js?v=46',
  './js/presence.js?v=46',
  './js/profile.js?v=46',
  './js/sound.js?v=46',
  './js/tutorials.js?v=46',
  './js/games/2048.js?v=46',
  './js/games/airhockey.js?v=46',
  './js/games/backgammon.js?v=46',
  './js/games/battleship.js?v=46',
  './js/games/breakthrough.js?v=46',
  './js/games/checkers.js?v=46',
  './js/games/chess.js?v=46',
  './js/games/chinese-checkers.js?v=46',
  './js/games/connect-four.js?v=46',
  './js/games/dominoes.js?v=46',
  './js/games/dots-boxes.js?v=46',
  './js/games/farkle.js?v=46',
  './js/games/go.js?v=46',
  './js/games/gomoku.js?v=46',
  './js/games/hangman.js?v=46',
  './js/games/hex.js?v=46',
  './js/games/level2048.js?v=46',
  './js/games/loa.js?v=46',
  './js/games/ludo.js?v=46',
  './js/games/mancala.js?v=46',
  './js/games/mastermind.js?v=46',
  './js/games/match3.js?v=46',
  './js/games/memory.js?v=46',
  './js/games/minesweeper.js?v=46',
  './js/games/nim.js?v=46',
  './js/games/nine-mens-morris.js?v=46',
  './js/games/number-duel.js?v=46',
  './js/games/onitama.js?v=46',
  './js/games/order-chaos.js?v=46',
  './js/games/pentago.js?v=46',
  './js/games/pig.js?v=46',
  './js/games/quarto.js?v=46',
  './js/games/quoridor.js?v=46',
  './js/games/reversi.js?v=46',
  './js/games/rock-paper-scissors.js?v=46',
  './js/games/sim.js?v=46',
  './js/games/snake.js?v=46',
  './js/games/snakes.js?v=46',
  './js/games/sudoku.js?v=46',
  './js/games/tetris.js?v=46',
  './js/games/tic-tac-toe.js?v=46',
  './js/games/tileboard.js?v=46',
  './js/games/tron.js?v=46',
  './js/games/ultimate-ttt.js?v=46',
  './js/games/word-race.js?v=46',
  './js/games/wordle-duel.js?v=46',
  './js/games/yahtzee.js?v=46',
  // MODULES:END
];

self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then((c) => Promise.all(SHELL.map((u) => c.add(u).catch(() => {})))));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  // Navigation -> serve cached index (offline fallback).
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('./index.html')));
    return;
  }
  // Cache-first with runtime caching (JS modules carry ?v=N so new deploys fetch fresh).
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((res) => {
    const copy = res.clone();
    caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
    return res;
  }).catch(() => hit)));
});
